name: CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: pipx install poetry
    - name: Install dependencies
      run: poetry install
    - name: Set git identity # Required for Git integration tests
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "hekonsek@gmail.com"
    - name: Run tests
      run: poetry run pytest

