name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install poetry
      run: pip install poetry
    - name: Install project dependencies
      run: poetry install
    - name: Set git identity
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "hekonsek@gmail.com"
    - name: Release version
      run: poetry run vrz minor --update-file=README.md
